web:
  host: "127.0.0.1"
  port: 8000
  secret_key: "your_secret_key"
  upload_dir: "web_upload"

watch_folder:
  dir: "watch_folder"
  validate_pdf_header: true
  processing_dir: "processing"

authentication:
  username: "admin"
  password_hash: "$2b$12$uG.SmnQ76mGiPy0wyztZkO4e/hoV3lo/3J8PEXITLC9ckfF3B3qAm" #password123

logging:
  log_file: "app.log"
  log_level: "INFO"
  log_format: "%(asctime)s %(levelname)s %(name)s %(message)s"

tasks:
  extract_document_data:
    module: standard_step.extraction.extract_pdf
    class: ExtractPdfTask
    params:
      api_key: "llx-CsOui2BBuQIAsd9tGmxWo3EdViSjz59L5nxitWDByvn100tT"
      agent_id: "f311fd08-282f-4fef-8a41-f728242159e9"
      fields:
        supplier_name:
          alias: "Supplier name"
          type: "str"
        purchase_order_number:
          alias: "Purchase Order number"
          type: "str"
        invoice_amount:
          alias: "Invoice Amount"
          type: "float"
        project_number:
          alias: "Project number"
          type: "Optional[str]"
    on_error: stop

  assign_nanoid:
    module: standard_step.context.assign_nanoid
    class: AssignNanoidTask
    params:
      length: 10
    on_error: stop

  store_metadata_json:
    module: standard_step.storage.store_metadata_as_json
    class: StoreMetadataAsJson
    params:
      data_dir: "data"
      filename: "{nanoid}_{purchase_order_number}_{supplier_name}"
    on_error: continue

  store_file_to_localdrive:
    module: standard_step.storage.store_file_to_localdrive
    class: StoreFileToLocaldrive
    params:
      files_dir: "files"
      filename: "{nanoid}_{purchase_order_number}_{supplier_name}"
    on_error: continue

  update_reference:
    module: standard_step.rules.update_reference
    class: UpdateReferenceTask
    params:
      reference_file: "reference_file/reference_file.csv"
      update_field: "MATCHED"
      write_value: "match_all"
      backup: true
      task_slug: "update_reference"
      csv_match:
        type: "column_equals_all"
        clauses:
          - column: "P/O NO."
            from_context: "purchase_order_number"
            number: false  # Force string comparison
          - column: "AMOUNT"
            from_context: "invoice_amount"
            number: true   # Force numeric comparison
    on_error: continue

pipeline:
   - extract_document_data
   - update_reference
   - assign_nanoid
   - store_metadata_json
   - store_file_to_localdrive