"""Browser lifecycle and screenshot verification with synthetic watch folders."""

from pathlib import Path

from playwright.sync_api import Page, expect
from test.visual.test_schema_review_visual import visual_app, page


EVIDENCE = Path("output/playwright/watch-folder-management")


def confirm(page: Page) -> None:
    page.locator('#watch-confirm button[value="confirm"]').click()


def test_watch_folder_lifecycle_and_visual_states(page: Page, visual_app, tmp_path: Path) -> None:
    EVIDENCE.mkdir(parents=True, exist_ok=True)
    folder = tmp_path / "synthetic-invoices-with-a-long-windows-folder-name"
    folder.mkdir()
    page.set_viewport_size({"width": 1440, "height": 1024})
    page.goto(f"{visual_app['base_url']}/app/admin/watch-folders")
    page.locator("#watch-add").click()
    expect(page.locator("#watch-existing-actions")).not_to_be_visible()
    page.locator("#watch-path").fill(str(folder))
    page.locator("#watch-test").click()
    expect(page.locator("#watch-check-result")).to_contain_text("passed")
    page.locator("#watch-pipeline").select_option(visual_app["active_template_id"])
    expect(page.locator("#watch-version")).not_to_have_value("")
    page.locator("#watch-enabled").check()
    page.locator("#watch-save").click()
    expect(page.locator("#watch-dialog")).not_to_be_visible()
    page.locator("#watch-search").fill(folder.name)
    row = page.locator("#watch-rows tr").filter(has_text=folder.name)
    expect(row).to_contain_text("enabled")
    row.get_by_role("button", name="Edit", exact=True).click()
    page.locator("#watch-version").select_option(index=2)
    page.locator("#watch-save").click()
    confirm(page)
    expect(row).to_contain_text("Update available")
    page.screenshot(path=str(EVIDENCE / "07-update-available.png"), full_page=True)
    row.get_by_role("button", name="Edit", exact=True).click()
    page.locator("#watch-upgrade").click()
    page.locator("#watch-save").click()
    confirm(page)
    expect(row).not_to_contain_text("Update available")
    page.screenshot(path=str(EVIDENCE / "01-table.png"), full_page=True)
    row.get_by_role("button", name="Edit", exact=True).click()
    page.screenshot(path=str(EVIDENCE / "02-edit-drawer.png"), full_page=True)
    page.keyboard.press("Escape")
    expect(row.get_by_role("button", name="Edit", exact=True)).to_be_focused()
    row.get_by_role("button", name="Pause", exact=True).click()
    confirm(page)
    expect(row).to_contain_text("paused")
    row.get_by_role("button", name="Resume", exact=True).click()
    confirm(page)
    expect(row).to_contain_text("enabled")
    row.get_by_role("button", name="Edit", exact=True).click()
    page.locator('[data-lifecycle="unbind"]').click()
    confirm(page)
    expect(row).to_contain_text("unbound")
    row.get_by_role("button", name="Edit", exact=True).click()
    page.locator("#watch-pipeline").select_option(visual_app["active_template_id"])
    expect(page.locator("#watch-version")).not_to_have_value("")
    page.locator("#watch-save").click()
    confirm(page)
    expect(row).to_contain_text("paused")
    row.get_by_role("button", name="Edit", exact=True).click()
    page.locator('[data-lifecycle="retire"]').click()
    confirm(page)
    expect(page.locator("#watch-rows")).to_contain_text("No watch folders")
    page.locator("#watch-retired").check()
    expect(row).to_contain_text("retired")
    row.get_by_role("button", name="Activity", exact=True).click()
    expect(page.locator("#watch-activity-body")).to_contain_text("watch_binding.retire")
    page.screenshot(path=str(EVIDENCE / "03-retired-history.png"), full_page=True)
    page.locator("#watch-activity-close").click()
    row.get_by_role("button", name="Activity", exact=True).click()
    page.get_by_role("link", name="View this folder in Reports").click()
    expect(page.locator("#reports-binding")).to_be_visible()
    expect(page.locator("#reports-binding-rows")).to_contain_text("No batches")
    page.goto(f"{visual_app['base_url']}/app/admin/watch-folders")
    page.locator("#watch-search").fill("no-match-synthetic")
    expect(page.locator("#watch-rows")).to_contain_text("No watch folders")
    page.screenshot(path=str(EVIDENCE / "04-empty-filter.png"), full_page=True)
    page.set_viewport_size({"width": 390, "height": 844})
    page.locator("#watch-add").click()
    expect(page.locator("#watch-path")).to_be_focused()
    expect(page.locator("#watch-existing-actions")).not_to_be_visible()
    page.screenshot(path=str(EVIDENCE / "05-mobile-drawer.png"), full_page=True)
    assert page.evaluate("document.documentElement.scrollWidth <= window.innerWidth")
    page.locator("#watch-cancel").click()


def test_unused_deletion_and_inaccessible_pause(page: Page, visual_app, tmp_path: Path) -> None:
    folder = tmp_path / "unused"
    folder.mkdir()
    page.goto(f"{visual_app['base_url']}/app/admin/watch-folders")
    page.locator("#watch-add").click()
    page.locator("#watch-path").fill(str(folder))
    page.locator("#watch-pipeline").select_option(visual_app["active_template_id"])
    expect(page.locator("#watch-version")).not_to_have_value("")
    page.locator("#watch-enabled").check()
    page.locator("#watch-save").click()
    expect(page.locator("#watch-dialog")).not_to_be_visible()
    folder.rmdir()
    page.locator("#watch-refresh").click()
    row = page.locator("#watch-rows tr").filter(has_text=str(folder))
    expect(row).to_contain_text("unhealthy")
    page.screenshot(path=str(EVIDENCE / "06-inaccessible.png"), full_page=True)
    row.get_by_role("button", name="Pause", exact=True).click()
    confirm(page)
    expect(row).to_contain_text("paused")
    row.get_by_role("button", name="Edit", exact=True).click()
    page.locator("#watch-delete").click()
    confirm(page)
    expect(row).to_have_count(0)
